config/routes.rb
HealthHackDublin::Application.routes.draw do
  resources :users

  resources :clinitian_messages

  resources :messages

  resources :homework_items

  resources :homeworks

  resources :moods

   root :to => 'index#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/clinitian.rb
class Clinitian < ActiveRecord::Base
  attr_accessible :jobTitle, :name, :password
end

app/models/clinitian_message.rb
class ClinitianMessage < ActiveRecord::Base
  attr_accessible :message, :mood_id
end

app/models/homework.rb
class Homework < ActiveRecord::Base
  attr_accessible :startDate, :title, :user_id
end

app/models/homework_item.rb
class HomeworkItem < ActiveRecord::Base
  attr_accessible :content, :done, :dueDate, :homework_id
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :message, :mood_id
end

app/models/mood.rb
class Mood < ActiveRecord::Base
  attr_accessible :message, :mood, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :clinitian_id, :name, :password
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
	def index
	end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	def index

	end

	def authenticate
		u = User.where(["name = ?", params[:user]]).first
		c = Clinitian.where(["name = ?", params[:user]]).first

		if u != nil

			if u.password == params[:password]

				session[:user] = params[:user]
				redirect_to :controller => "dashboard", :action => "index"

			end
		
		elsif c != nil

			#if c.password == params[:password]

				session[:clinitian] = params[:user]
				redirect_to :controller => "dashboard", :action => "index"

			#end

		else

			redirect_to :controller => "login", :action => "index"
		end

	end
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  # GET /moods
  # GET /moods.json
  def index
    #if session[:clinitian] != nil
      #c = Clinitian.where(['name = ?', session[:clinitian] ]).first

      #@mood = Mood.join("INNER JOIN users on
      #                  moods.user_id = users.id").where(['
      #                  users.clinitian_id = ?',c.id ])
    #elsif session[:user] != nil
    #  u = User.where(["name = ?", session[:user]]).first
    #  @mood = Mood.where(["user_id = ?", u.id ])
    #else
    #  @mood = Mood.all
    #end
    @moods = Mood.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @moods }
    end 
  end

  # GET /moods/1
  # GET /moods/1.json
  def show
    @mood = Mood.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mood }
    end
  end

  # GET /moods/new
  # GET /moods/new.json
  def new
    @mood = Mood.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mood }
    end
  end

  # GET /moods/1/edit
  def edit
    @mood = Mood.find(params[:id])
  end

  # POST /moods
  # POST /moods.json
  def create
    @mood = Mood.new(params[:mood])

    respond_to do |format|
      if @mood.save
        format.html { redirect_to @mood, notice: 'Mood was successfully created.' }
        format.json { render json: @mood, status: :created, location: @mood }
      else
        format.html { render action: "new" }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /moods/1
  # PUT /moods/1.json
  def update
    @mood = Mood.find(params[:id])

    respond_to do |format|
      if @mood.update_attributes(params[:mood])
        format.html { redirect_to @mood, notice: 'Mood was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moods/1
  # DELETE /moods/1.json
  def destroy
    @mood = Mood.find(params[:id])
    @mood.destroy

    respond_to do |format|
      format.html { redirect_to moods_url }
      format.json { head :no_content }
    end
  end

  def comment 
  
    mood_id = session[:mood_id]
    session[:mood_id] = nil

    Message.create([{ message: params[:message], mood_id: mood_id }])

    redirect_to :controller => '/moods', id: mood_id

  end

  def commentClinitians
  
    mood_id = session[:mood_id]
    session[:mood_id] = nil

    ClinitianMessage.create([{ message: params[:message], mood_id: mood_id }])

    redirect_to :controller => '/moods', id: mood_id

  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def index
		u = User.where(["id = ?",params[:userID]])

		@m = Message.joins("INNER JOIN moods on messages.mood_id = moods.id
						    INNER JOIN users on moods.user_id = users.id").where(["
						    users.id = ?",params[:userID]])
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/moods/_form.html.erb
<%= form_for(@mood) do |f| %>
  <% if @mood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mood.errors.count, "error") %> prohibited this mood from being saved:</h2>

      <ul>
      <% @mood.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :mood %><br />
    <%= f.number_field :mood %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moods/edit.html.erb
<h1>Editing mood</h1>

<%= render 'form' %>

<%= link_to 'Show', @mood %> |
<%= link_to 'Back', moods_path %>

app/views/moods/index.html.erb
<h1>Listing moods</h1>

<table>
  <tr>
    <th>Message</th>
    <th>Mood</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @moods.each do |mood| %>
  <tr>
    <td><%= mood.message %></td>
    <td><%= mood.mood %></td>
    <td><%= mood.user_id %></td>
    <td><%= link_to 'Show', mood %></td>
    <td><%= link_to 'Edit', edit_mood_path(mood) %></td>
    <td><%= link_to 'Destroy', mood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mood', new_mood_path %>

app/views/moods/new.html.erb
<h1>New mood</h1>

<%= render 'form' %>

<%= link_to 'Back', moods_path %>

app/views/moods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @mood.message %>
</p>

<p>
  <b>Mood:</b>
  <%= @mood.mood %>
</p>

<p>
  <b>User:</b>
  <%= @mood.user_id %>
</p>

<% if session[:user] != nil %>
	<% session[:mood_id] = @mood.id %>

	<%= form_tag("/moods/comment", :method => "post") do %>

	<%= text_area_tag(:message) %><br/>

	<%= submit_tag("Add Comment", :class => 'btn primary')%>

	<%end%>
<% end %>

<% if session[:clinitian] != nil %>
	<% session[:mood_id] = @mood.id %>

	<%= form_tag("/moods/commentClinitians", :method => "post") do %>

	<%= text_area_tag(:message) %><br/>

	<%= submit_tag("Add Comment", :class => 'btn primary')%>

	<%end%>
<% end %>


<%= link_to 'Edit', edit_mood_path(@mood) %> |
<%= link_to 'Back', moods_path %>