config/routes.rb
HealthHackDublin::Application.routes.draw do
  resources :users

  resources :clinitian_messages

  resources :messages

  resources :homework_items

  resources :homeworks

  resources :moods

   root :to => 'index#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/clinitian.rb
class Clinitian < ActiveRecord::Base
  attr_accessible :jobTitle, :name, :password
end

app/models/clinitian_message.rb
class ClinitianMessage < ActiveRecord::Base
  attr_accessible :message, :mood_id
end

app/models/homework.rb
class Homework < ActiveRecord::Base
  attr_accessible :startDate, :title, :user_id
end

app/models/homework_item.rb
class HomeworkItem < ActiveRecord::Base
  attr_accessible :content, :done, :dueDate, :homework_id
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :message, :mood_id
end

app/models/mood.rb
class Mood < ActiveRecord::Base
  attr_accessible :message, :mood, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :clinitian_id, :name, :password
end

app/controllers/clinitian_messages_controller.rb
class ClinitianMessagesController < ApplicationController
  # GET /clinitian_messages
  # GET /clinitian_messages.json
  def index
    @clinitian_messages = ClinitianMessage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clinitian_messages }
    end
  end

  # GET /clinitian_messages/1
  # GET /clinitian_messages/1.json
  def show
    @clinitian_message = ClinitianMessage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clinitian_message }
    end
  end

  # GET /clinitian_messages/new
  # GET /clinitian_messages/new.json
  def new
    @clinitian_message = ClinitianMessage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clinitian_message }
    end
  end

  # GET /clinitian_messages/1/edit
  def edit
    @clinitian_message = ClinitianMessage.find(params[:id])
  end

  # POST /clinitian_messages
  # POST /clinitian_messages.json
  def create
    @clinitian_message = ClinitianMessage.new(params[:clinitian_message])

    respond_to do |format|
      if @clinitian_message.save
        format.html { redirect_to @clinitian_message, notice: 'Clinitian message was successfully created.' }
        format.json { render json: @clinitian_message, status: :created, location: @clinitian_message }
      else
        format.html { render action: "new" }
        format.json { render json: @clinitian_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clinitian_messages/1
  # PUT /clinitian_messages/1.json
  def update
    @clinitian_message = ClinitianMessage.find(params[:id])

    respond_to do |format|
      if @clinitian_message.update_attributes(params[:clinitian_message])
        format.html { redirect_to @clinitian_message, notice: 'Clinitian message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clinitian_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinitian_messages/1
  # DELETE /clinitian_messages/1.json
  def destroy
    @clinitian_message = ClinitianMessage.find(params[:id])
    @clinitian_message.destroy

    respond_to do |format|
      format.html { redirect_to clinitian_messages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
	def index
	end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	def index

	end

	def authenticate
		u = User.where(["name = ?", params[:user]]).first
		c = Clinitian.where(["name = ?", params[:user]]).first

		if u != nil

			if u.password == params[:password]

				session[:user] = params[:user]
				redirect_to :controller => "dashboard", :action => "index"

			end
		
		elsif c != nil

			#if c.password == params[:password]

				session[:clinitian] = params[:user]
				redirect_to :controller => "dashboard", :action => "index"

			#end

		else

			redirect_to :controller => "login", :action => "index"
		end

	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def index
		u = User.where(["id = ?",params[:userID]])

		@m = Message.joins("INNER JOIN moods on messages.mood_id = moods.id
						    INNER JOIN users on moods.user_id = users.id").where(["
						    users.id = ?",params[:userID]])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinitian_messages_helper.rb
module ClinitianMessagesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clinitian_messages/_form.html.erb
<%= form_for(@clinitian_message) do |f| %>
  <% if @clinitian_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clinitian_message.errors.count, "error") %> prohibited this clinitian_message from being saved:</h2>

      <ul>
      <% @clinitian_message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :mood_id %><br />
    <%= f.number_field :mood_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clinitian_messages/edit.html.erb
<h1>Editing clinitian_message</h1>

<%= render 'form' %>

<%= link_to 'Show', @clinitian_message %> |
<%= link_to 'Back', clinitian_messages_path %>

app/views/clinitian_messages/index.html.erb
<h1>Listing clinitian_messages</h1>

<table>
  <tr>
    <th>Message</th>
    <th>Mood</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clinitian_messages.each do |clinitian_message| %>
  <tr>
    <td><%= clinitian_message.message %></td>
    <td><%= clinitian_message.mood_id %></td>
    <td><%= link_to 'Show', clinitian_message %></td>
    <td><%= link_to 'Edit', edit_clinitian_message_path(clinitian_message) %></td>
    <td><%= link_to 'Destroy', clinitian_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Clinitian message', new_clinitian_message_path %>

app/views/clinitian_messages/new.html.erb
<h1>New clinitian_message</h1>

<%= render 'form' %>

<%= link_to 'Back', clinitian_messages_path %>

app/views/clinitian_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @clinitian_message.message %>
</p>

<p>
  <b>Mood:</b>
  <%= @clinitian_message.mood_id %>
</p>


<%= link_to 'Edit', edit_clinitian_message_path(@clinitian_message) %> |
<%= link_to 'Back', clinitian_messages_path %>