config/routes.rb
HealthHackDublin::Application.routes.draw do
  resources :users

  resources :clinitian_messages

  resources :messages

  resources :homework_items

  resources :homeworks

  resources :moods

   root :to => 'index#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/clinitian.rb
class Clinitian < ActiveRecord::Base
  attr_accessible :jobTitle, :name, :password
end

app/models/clinitian_message.rb
class ClinitianMessage < ActiveRecord::Base
  attr_accessible :message, :mood_id
end

app/models/homework.rb
class Homework < ActiveRecord::Base
  attr_accessible :startDate, :title, :user_id
end

app/models/homework_item.rb
class HomeworkItem < ActiveRecord::Base
  attr_accessible :content, :done, :dueDate, :homework_id
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :message, :mood_id
end

app/models/mood.rb
class Mood < ActiveRecord::Base
  attr_accessible :message, :mood, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :clinitian_id, :name, :password
end

app/controllers/homework_items_controller.rb
class HomeworkItemsController < ApplicationController
  # GET /homework_items
  # GET /homework_items.json
  def index
    @homework_items = HomeworkItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homework_items }
    end
  end

  # GET /homework_items/1
  # GET /homework_items/1.json
  def show
    @homework_item = HomeworkItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @homework_item }
    end
  end

  # GET /homework_items/new
  # GET /homework_items/new.json
  def new
    @homework_item = HomeworkItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @homework_item }
    end
  end

  # GET /homework_items/1/edit
  def edit
    @homework_item = HomeworkItem.find(params[:id])
  end

  # POST /homework_items
  # POST /homework_items.json
  def create
    @homework_item = HomeworkItem.new(params[:homework_item])

    respond_to do |format|
      if @homework_item.save
        format.html { redirect_to @homework_item, notice: 'Homework item was successfully created.' }
        format.json { render json: @homework_item, status: :created, location: @homework_item }
      else
        format.html { render action: "new" }
        format.json { render json: @homework_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homework_items/1
  # PUT /homework_items/1.json
  def update
    @homework_item = HomeworkItem.find(params[:id])

    respond_to do |format|
      if @homework_item.update_attributes(params[:homework_item])
        format.html { redirect_to @homework_item, notice: 'Homework item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @homework_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homework_items/1
  # DELETE /homework_items/1.json
  def destroy
    @homework_item = HomeworkItem.find(params[:id])
    @homework_item.destroy

    respond_to do |format|
      format.html { redirect_to homework_items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
	def index
	end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	def index

	end

	def authenticate
		u = User.where(["name = ?", params[:user]]).first
		c = Clinitian.where(["name = ?", params[:user]]).first

		if u != nil

			if u.password == params[:password]

				session[:user] = params[:user]
				redirect_to :controller => "dashboard", :action => "index"

			end
		
		elsif c != nil

			#if c.password == params[:password]

				session[:clinitian] = params[:user]
				redirect_to :controller => "dashboard", :action => "index"

			#end

		else

			redirect_to :controller => "login", :action => "index"
		end

	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def index
		u = User.where(["id = ?",params[:userID]])

		@m = Message.joins("INNER JOIN moods on messages.mood_id = moods.id
						    INNER JOIN users on moods.user_id = users.id").where(["
						    users.id = ?",params[:userID]])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homework_items_helper.rb
module HomeworkItemsHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homework_items/_form.html.erb
<%= form_for(@homework_item) do |f| %>
  <% if @homework_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homework_item.errors.count, "error") %> prohibited this homework_item from being saved:</h2>

      <ul>
      <% @homework_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :done %><br />
    <%= f.check_box :done %>
  </div>
  <div class="field">
    <%= f.label :dueDate %><br />
    <%= f.date_select :dueDate %>
  </div>
  <div class="field">
    <%= f.label :homework_id %><br />
    <%= f.number_field :homework_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homework_items/edit.html.erb
<h1>Editing homework_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @homework_item %> |
<%= link_to 'Back', homework_items_path %>

app/views/homework_items/index.html.erb
<h1>Listing homework_items</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Done</th>
    <th>Duedate</th>
    <th>Homework</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @homework_items.each do |homework_item| %>
  <tr>
    <td><%= homework_item.content %></td>
    <td><%= homework_item.done %></td>
    <td><%= homework_item.dueDate %></td>
    <td><%= homework_item.homework_id %></td>
    <td><%= link_to 'Show', homework_item %></td>
    <td><%= link_to 'Edit', edit_homework_item_path(homework_item) %></td>
    <td><%= link_to 'Destroy', homework_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Homework item', new_homework_item_path %>

app/views/homework_items/new.html.erb
<h1>New homework_item</h1>

<%= render 'form' %>

<%= link_to 'Back', homework_items_path %>

app/views/homework_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @homework_item.content %>
</p>

<p>
  <b>Done:</b>
  <%= @homework_item.done %>
</p>

<p>
  <b>Duedate:</b>
  <%= @homework_item.dueDate %>
</p>

<p>
  <b>Homework:</b>
  <%= @homework_item.homework_id %>
</p>


<%= link_to 'Edit', edit_homework_item_path(@homework_item) %> |
<%= link_to 'Back', homework_items_path %>